// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_HNAGLTGgSYCZ3AG1J0zen3-ftPl5L4',
    appId: '1:332992392606:web:9c143e89d808da8a4bba8f',
    messagingSenderId: '332992392606',
    projectId: 'tokio-2ab9a',
    authDomain: 'tokio-2ab9a.firebaseapp.com',
    storageBucket: 'tokio-2ab9a.firebasestorage.app',
    measurementId: 'G-PE7PCHKDK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHIS5ynGqtwdhdS2Ak9fBCwHhL2-3K03U',
    appId: '1:332992392606:android:83748645048b47384bba8f',
    messagingSenderId: '332992392606',
    projectId: 'tokio-2ab9a',
    storageBucket: 'tokio-2ab9a.firebasestorage.app',
  );
}
